apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: deploy-helm-chart
description: 'Deploy Helm chart'

inputs:
  deploy-branch:
    description: 'Deploy branch'
    required: false
    default: 'main'
  namespace:
    description: 'Namespace to deploy to'
    required: false
    default: 'platform'
  consule-service-name:
    description: 'Consule service name'
    required: false
  cb-internal-db-service:
    description: 'cb-internal-db-service to install for feature branch'
    default: 'false'
  cb-internal-nats:
    description: 'cb-internal-nats to install for feature branch'
    default: 'false'
  install-type:
    description: 'Install type'
    required: true
  chart-location:
    description: 'Install type'
    required: false
  chart-version:
    description: 'Install type'
    required: false
  release-name:
    description: 'Install type'
    required: false
  values:
    description: 'values for helm-install'
    required: false
  registry-root:
    description: 'The host (and port) where the charts and container images are pulled from (use `vars.STAGING_DOCKER_REGISTRY`)'
    required: true  
  image-registry:
    description: 'The host (and port) and path where the container images are pulled from, normally a sub-path of registry-root, (use `vars.STAGING_IMAGE_REGISTRY`)'
    required: true

runs:
  using: composite
  steps:
      - id: install-chart
        name: Install reports-service helm chart
        uses: cloudbees-io/helm-install@v1
        kind: deploy
        if: ${{ inputs.install-type == 'helm-install' }}
        with:
          chart-location: ${{ inputs.chart-location }}
          version: ${{ inputs.chart-version }}
          release-name: ${{ inputs.release-name }}
          namespace: ${{ inputs.namespace }}
          values: |
            ${{ inputs.values }}
