apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: deploy-dependencies
description: "Deploy nats dependencies"

inputs:
  chart-registry:
    description: "The chart registry to pull charts from"
    required: true
  oidc-iam-role:
    description: "OIDC IAM Role for AWS Login"
    required: false
  cluster-name:
    description: "OIDC IAM Role for AWS Login"
    required: false

runs:
  using: composite
  steps:
    - name: Login to AWS
      uses: cloudbees-io/configure-aws-credentials@v1
      id: aws-login
      with:
        aws-region: us-east-1
        role-to-assume: ${{ inputs.oidc-iam-role }}
        role-duration-seconds: "3600" # optionally set the duration of the login token

    - name: Configure container registry for Staging ECR
      uses: cloudbees-io/configure-ecr-credentials@v1

    - uses: cloudbees-io/configure-eks-credentials@v1
      with:
        name: ${{ inputs.cluster-name }}

    - id: createns
      name: Create Kubernetes Namespace
      uses: cloudbees-io/create-k8s-namespace@v1
      with:
        name: ${{ cloudbees.scm.branch == 'main' && 'platform' || format('{0}-{1}-{2}', cloudbees.scm.branch, cloudbees.scm.repository, cloudbees.scm.sha) }}
        sanitize-name: ${{ cloudbees.scm.branch != 'main' }}
        labels: |
          cloudbees.io/cleanup: "${{ cloudbees.scm.branch != 'main' }}"

    - id: install-nats
      name: Install NATS
      if: ${{ cloudbees.scm.branch != 'main' }}
      uses: https://github.com/calculi-corp/nats/actions/deploy:main
      with:
        namespace: ${{ steps.createns.outputs.name }}
        chart-location: oci://${{ inputs.chart-registry }}/nats