apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: cleanup-deployments
description: 'Cleanup deployments'

inputs:
  namespace:
    description: 'Namespace where the chart will be installed'
    required: true
  release-name:
    description: "Name of the Helm release"
    required: true

runs:
  using: composite
  steps:
    - name: Uninstall ${{ inputs.release-name }} Helm chart
      uses: cloudbees-io/helm-uninstall@v1
      with:
        release-name: ${{ inputs.release-name }}
        namespace: ${{ inputs.namespace }}

    - name: Uninstall db-service chart
      uses: cloudbees-io/helm-uninstall@v1
      with:
        release-name: db-service
        namespace: ${{ inputs.namespace }}

    - name: Uninstall NATS
      uses: cloudbees-io/helm-uninstall@v1
      with:
        release-name: nats
        namespace: ${{ inputs.namespace }}