apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

env:
  application_name: test-data-ingestion-2

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  unit-test-and-scan:
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1
      - id: unit-test-and-scan
        name: Run Unit test
        uses: calculi-corp/cb-internal-shared-actions/build@v3
        with:
          run-unit-test: "true"
          go-binary-build: "false"
          kaniko-build: "false"
          trivy-scan-container: "false"
          unit-test-percent: "81"
          
  build: 
      outputs:
        tag: ${{ steps.build-container.outputs.tag-digest }}
      steps:
        - name: Get source code
          uses: cloudbees-io/checkout@v1
  
        - name: Setup git credentials
          uses: cloudbees-io/configure-git-global-credentials@v1
  
        - id: build-go-binary
          name: Build Go binary
          uses: docker://golang:latest
          kind: build
          run: |
            GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags \"-static\"' -o reports-service --buildvcs=0
          env:
            CGO_ENABLED: "0"
  
